INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES (1, 'INSTRUMENT1', 2.5);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES (2, 'INSTRUMENT2', 1.3);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES (3, 'INSTRUMENT3', 1.7);